version: '3.8'

services:
  quantum_db:
    image: postgres:13
    container_name: quantum_postgres_db
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - quantum_docker_network
    ports:
      - '${DB_PORT}:${DB_PORT}'

  quantum_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: quantum_api_service
    env_file:
      - .env
    environment:
      DB_HOST: quantum_db
    depends_on:
      - quantum_db
    networks:
      - quantum_docker_network
    ports:
      - '${PORT}:${PORT}'

networks:
  quantum_docker_network:
    driver: bridge
