# ./docker-compose.db.yml
version: '3.8'

services:
  quantum_db:
    image: postgres:13
    container_name: quantum_postgres_db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    networks:
      - quantum_docker_network
    ports:
      - '${DB_PORT}:${DB_PORT}'

networks:
  quantum_docker_network:
    driver: bridge
